#! /usr/bin/env python3 


import os
import sys
import urllib
import subprocess
from urllib.request import urlopen


DIR_DOTFILES = '~/.dotfiles'
DIR_OH_MY_ZSH = '~/.oh-my-zsh'
DIR_PYENV_ROOT = ''

URL_OH_MY_ZSH = 'https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh'


packages = [
    "autojump", "pyenv", "pyenv-virtualenv",
    "proxychains-ng", "node", "tmux", "yarn",
    "gnu-sed", "cmake", "pipenv",
    "mosh", "docker", "docker-machine",
    "zsh-syntax-highlighting", "neovim"
]



def install_oh_my_zsh(url):
    # sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    res = urlopen(url)
    data = res.read().decode('utf-8')
    print(data)




def install_packages(package_list):
    pass



if __name__ == '__main__':
    # install_oh_my_zsh(URL_OH_MY_ZSH)
    try:
        a = subprocess.run('false', check=True)
    except subprocess.CalledProcessError as error:
        print(error)
